-- CreateTable
CREATE TABLE "HomeContent" (
    "id" TEXT NOT NULL DEFAULT 'home',
    "heroEyebrow" TEXT NOT NULL,
    "heroTitleLine1" TEXT NOT NULL,
    "heroTitleLine2" TEXT NOT NULL,
    "heroTitleAccent" TEXT NOT NULL,
    "heroSubtitle" TEXT NOT NULL,
    "heroPrimaryCtaLabel" TEXT NOT NULL,
    "heroPrimaryCtaHref" TEXT NOT NULL,
    "heroSecondaryCtaLabel" TEXT NOT NULL,
    "heroSecondaryCtaHref" TEXT NOT NULL,
    "missionEyebrow" TEXT NOT NULL,
    "missionTitle" TEXT NOT NULL,
    "missionTitleAccent" TEXT NOT NULL,
    "missionBody" TEXT NOT NULL,
    "visionEyebrow" TEXT NOT NULL,
    "visionTitle" TEXT NOT NULL,
    "visionTitleAccent" TEXT NOT NULL,
    "visionBody" TEXT NOT NULL,
    "storyEyebrow" TEXT NOT NULL,
    "storyHeading" TEXT NOT NULL,
    "storyParagraph1" TEXT NOT NULL,
    "storyParagraph2" TEXT NOT NULL,
    "stat1Value" INTEGER NOT NULL,
    "stat1Label" TEXT NOT NULL,
    "stat2Value" INTEGER NOT NULL,
    "stat2Label" TEXT NOT NULL,
    "stat3Value" INTEGER NOT NULL,
    "stat3Label" TEXT NOT NULL,
    "insideEyebrow" TEXT NOT NULL,
    "insideTitleStart" TEXT NOT NULL,
    "insideTitleAccent" TEXT NOT NULL,
    "insideSubtitle" TEXT NOT NULL,
    "insideTile1Label" TEXT NOT NULL,
    "insideTile2Label" TEXT NOT NULL,
    "insideTile3Label" TEXT NOT NULL,
    "insideTile4Label" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HomeContent_pkey" PRIMARY KEY ("id")
);
